//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techtouch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web.Mvc;
    
    public partial class Product
    {
        public Product()
        {
            this.Orders = new HashSet<Order>();
        }

        public int product_id { get; set; }
        [DisplayName("Name")]
        [Required(ErrorMessage = "Product name must be added")]
        public string product_name { get; set; }
        [Required(ErrorMessage = "Price must be added")]
        [DisplayName("Price")]
        public double product_price { get; set; }
        [DisplayName("Description")]
        [DataType(DataType.MultilineText)]
        public string product_description { get; set; }
        [DisplayName("Product Type")]
        public int product_type_id { get; set; }
        [DisplayName("Product Image")]
        public byte[] product_image { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
